// Generated by CoffeeScript 1.10.0
(function() {
  var polymerReady;

  polymerReady = new ReactiveVar(false);

  $(window).on("polymer-ready", function() {
    return polymerReady.set(true);
  });

  Meteor.startup(function() {
    $("body").append("<div fit layout vertical iron-router></div>");
    return Tracker.autorun(function() {
      if (polymerReady.get()) {
        Router.insert({
          el: "[iron-router]"
        });
        return Router.start();
      }
    });
  });

}).call(this);
