// Generated by CoffeeScript 1.10.0
(function() {
  Meteor.startup(function() {
    return Inject.rawModHtml('addUnresolved', function(html) {
      return html = html.replace('<body>', '<body unresolved fit layout vertical>');
    });
  });

}).call(this);
