app:
  build: .
  expose:
    - "80"
  ports:
    - "80"
  volumes:
    - ".:/app"
  container_name: app

redis:
  expose:
    - "6379"
  image: tutum/redis 
  environment:
    - 'REDIS_PASS="allowcache"'
  container_name: redis

db:
  build: ./db/ 
  expose:
    - "3306"
  container_name: mysql

