// Generated by CoffeeScript 1.10.0
(function() {
  Template.signIn.events({
    "submit [data-action=sign-in]": function(e) {
      var $form, email, pass;
      $form = $(e.target);
      if ($form[0].valid) {
        email = $form.find("#email").val();
        pass = $form.find("#password").val();
        return Meteor.loginWithPassword(email, pass, function(error) {
          if (error) {
            return GlobalUI.toast(error.reason);
          } else {
            return Router.go("home");
          }
        });
      }
    }
  });

}).call(this);
